### ISSUE TITLE
JamfUploaderSlacker error - TypeError: curl() got an unexpected keyword argument 'method'

### ISSUE THREAD

**Issue by rtrouton** [autopkg/grahampugh-recipes#92]
I'm trying to use the JamfUploaderSlacker processor to post the output of a Jamf Upload run to Slack, but I'm seeing the following error:

`TypeError: curl() got an unexpected keyword argument 'method'`

Error in context:

```
com.github.grahampugh.jamf-upload.processors/JamfUploaderSlacker
{'Input': {'JSS_URL': 'https://jamf-pro.server.here',
           'NAME': 'Poly Lens',
           'jamfpackageuploader_summary_result': {'data': {'category': 'Apps',
                                                           'pkg_name': 'Poly_Lens_1.1.11.pkg',
                                                           'pkg_path': '/Users/username/Library/AutoPkg/Cache/local.jamf.PolyLens/Poly_Lens_1.1.11.pkg',
                                                           'version': '1.1.11'},
                                                  'report_fields': ['pkg_path',
                                                                    'pkg_name',
                                                                    'version',
                                                                    'category'],
                                                  'summary_text': 'The '
                                                                  'following '
                                                                  'packages '
                                                                  'were '
                                                                  'uploaded to '
                                                                  'or updated '
                                                                  'in Jamf '
                                                                  'Pro:'},
           'pkg_name': 'Poly_Lens_1.1.11.pkg',
           'slack_webhook_url': 'https://hooks.slack.com/services/904324BF/178BF71E2FB4/80f35feb9d418b6897e3'}}
JamfUploaderSlacker: No value supplied for slack_username, setting default value of: AutoPkg
JamfUploaderSlacker: No value supplied for slack_icon_url, setting default value of: 
JamfUploaderSlacker: JSS address: https://jamf-pro.server.here
JamfUploaderSlacker: Title: Poly Lens
JamfUploaderSlacker: Policy: None
JamfUploaderSlacker: Version: 1.1.11
JamfUploaderSlacker: Package: Poly_Lens_1.1.11.pkg
JamfUploaderSlacker: Package Category: None
JamfUploaderSlacker: Policy Category: None
JamfUploaderSlacker: Slack webhook post attempt 1
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Users/username/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahampugh-recipes/JamfUploaderProcessors/JamfUploaderSlacker.py", line 182, in main
    method="POST", url=slack_webhook_url, data=slack_json, auth=""
TypeError: curl() got an unexpected keyword argument 'method'
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
curl() got an unexpected keyword argument 'method'
Failed.
Receipt written to /Users/username/Library/AutoPkg/Cache/local.jamf.PolyLens/receipts/local.jamf-receipt-20220205-205613.plist

The following recipes failed:
    local.jamf.PolyLens
        Error in local.jamf.PolyLens: Processor: com.github.grahampugh.jamf-upload.processors/JamfUploaderSlacker: Error: curl() got an unexpected keyword argument 'method'
```

Everything appears to be working correctly with the recipe run until the error for JamfUploaderSlacker. Full verbose output available here:

https://gist.github.com/rtrouton/3e708cf52b6e04d1db666e49be100800

**Comment by grahampugh** [comment]
Thanks for the heads up. I'm pretty sure I know the fix ("method" changed to "request") but I never tested the Slacker processor as I don't use it. I'll take a look in the morning.

**Comment by grahampugh** [comment]
@rtrouton I've pushed a fix, though I need to write a test script to actually verify it. Give it a try and let me know if it's working now.

**Comment by rtrouton** [comment]
Issue was resolved by the fix, closing issue.
